name: Run flatpak-builder-lint
description: Runs flatpak-builder-lint with exceptions
inputs:
  artifact:
    description: Type of artifact to lint (builddir, repo, manifest, appstream)
    required: true
  path:
    description: Path to flatpak-builder manifest or Flatpak build directory
    required: true
  workingDirectory:
    description: Working directory to clone flatpak-builder-lint
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - name: Check artifact type
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        : Check artifact input
        if ! [[ "${{ inputs.artifact }}" =~ builddir|repo|manifest|appstream ]]; then
          echo "::error::Given artifact type is incorrect"
          exit 2
        fi

    - name: Run flatpak-builder-lint
      id: result
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        : Run flatpak-builder-lint

        flatpak-builder-lint --exceptions ${{ inputs.artifact }} ${{ inputs.path }}
