name: Build (New)
on:
  push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        program:
        - ares
        config:
        - RelWithDebInfo
        platform:
        - name: windows-x64
          os: windows-latest
          compiler: clang++
          shell: 'msys2 {0}'
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang
          target-cmake-preset: windows-ci-mingw-native
        - name: windows-arm64
          os: windows-latest
          shell: 'msys2 {0}'
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang mingw-w64-clang-aarch64-clang mingw-w64-cross-clang-toolchain
          target-cmake-preset: windows-ci-mingw-cross
          native-cmake-preset: windows-ci-mingw-native
        - name: windows-clang-cl-x64
          os: windows-latest
          windres: rc
          shell: bash
          target-cmake-preset: windows-ci-cl-native
        - name: windows-clang-cl-arm64
          os: windows-latest
          windres: rc
          shell: bash
          target-cmake-preset: windows-ci-cl-cross
          native-cmake-preset: windows-ci-cl-native
        - name: macos-compat
          os: macos-12
          compiler: clang++
          shell: sh
          install: cmake ccache
          target-cmake-preset: macos-ci-compat
        - name: macos-latest
          os: macos-latest
          compiler: clang++
          shell: sh
          install: cmake ccache xcbeautify
          target-cmake-preset: macos-ci-latest
    name: ${{ matrix.program }}-${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - name: Install MSYS2 Dependencies
      if: matrix.platform.shell == 'msys2 {0}'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.platform.msystem }}
        install: make git cmake ccache ninja ${{ matrix.platform.install }}
    - name: "macOS: Import Certificate"
      if: runner.os == 'macOS' && github.event_name != 'pull_request'
      continue-on-error: ${{ github.repository != 'ares-emulator/ares' }}
      uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE_DATA }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PASSPHRASE }}
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install ${{ matrix.platform.install }}
    - name: "Build: Windows"
      if: runner.os != 'macOS'
      run: .github/scripts/build_windows.sh
      env:
        CROSS_COMPILE: ${{ matrix.platform.native-cmake-preset != '' }}
        NATIVE_PRESET: ${{ matrix.platform.native-cmake-preset }}
        TARGET_PRESET: ${{ matrix.platform.target-cmake-preset }}
    - name: "Build: macOS"
      if: runner.os == 'macOS'
      run: .github/scripts/build_macos.sh
      env:
        TARGET_PRESET: ${{ matrix.platform.target-cmake-preset }}
        MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
        MACOS_NOTARIZATION_TEAMID: ${{ secrets.MACOS_NOTARIZATION_TEAMID }}
        MACOS_KEYCHAIN_NAME: ares-macos-keychain
        MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
    - name: "Windows: sign"
      if: runner.os == 'Windows' && needs.pr-check.outputs.number != null
      uses: DanaBear/code-sign-action@98c79121b376beab8d6a9484f445089db4461bca
      with:
        certificate: '${{ secrets.WIN_CERTIFICATE }}'
        password: '${{ secrets.WIN_PASSWORD }}'
        certificatesha1: '${{ secrets.WIN_CERTHASH }}'
        certificatename: '${{ secrets.WIN_CERTNAME }}'
        folder: 'build/desktop-ui/rundir/'
        timestampUrl: 'http://timestamp.digicert.com'
    - name: "macOS: notarize"
      if: runner.os == 'macOS' && needs.pr-check.outputs.number != null
      continue-on-error: ${{ github.repository != 'ares-emulator/ares' }}
      run: |
        ditto -c -k --keepParent desktop-ui/RelWithDebInfo/ares.app /tmp/ares.zip
        xcrun notarytool submit /tmp/ares.zip --apple-id "$MACOS_NOTARIZATION_USERNAME" --password "$MACOS_NOTARIZATION_PASSWORD" --team-id "$MACOS_NOTARIZATION_TEAMID" --wait
        xcrun stapler staple desktop-ui/RelWithDebInfo/ares.app
      env:
        MACOS_NOTARIZATION_USERNAME: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
        MACOS_NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
        MACOS_NOTARIZATION_TEAMID: ${{ secrets.MACOS_NOTARIZATION_TEAMID }}
    - name: Upload Build (Windows)
      if: runner.os != 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.platform.name }}
        path: build/desktop-ui/rundir/*
    - name: Upload Build (macOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.platform.name }}
        path: build/desktop-ui/RelWithDebInfo/
    - name: Upload Debug Symbols (Windows)
      if: runner.os != 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.platform.name }}-PDBs
        path: build/PDBs/*
    - name: Upload Debug Symbols (macOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.platform.name }}-dSYMs
        path: build/dSYMs/*
        
  release:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
    - uses: actions/checkout@v4
      with:
        path: 'src'
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: 'bin'
    - name: Package Artifacts
      run: .github/scripts/package_artifacts.sh
    - name: Create Release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -eu
        github_rest()
        {
          local method="${1}"
          local url="https://api.github.com${2}"
          shift 2
          >&2 echo "${method} ${url}"
          curl \
            --fail \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -X "${method}" \
            "${url}" \
            "$@"
        }
        github_get_release_id_for_tag()
        {
          payload=$(github_rest GET "/repos/${GITHUB_REPOSITORY}/releases/tags/${1}") || return
          echo "${payload}" | jq .id
        }
        github_delete_release_by_id()
        {
          github_rest DELETE "/repos/${GITHUB_REPOSITORY}/releases/${1}"
        }
        github_create_release()
        {
          local payload="{
            \"tag_name\": \"${1}\",
            \"target_commitish\": \"${2}\",
            \"name\": \"${3}\",
            \"body\": \"${4}\",
            \"draft\": ${5},
            \"prerelease\": ${6}
          }"
          github_rest POST "/repos/${GITHUB_REPOSITORY}/releases" -d "${payload}"
        }
        make_nightly_release()
        {
          github_create_release \
            nightly \
            "${GITHUB_SHA}" \
            "ares nightly $(date +"%Y-%m-%d")" \
            "Auto-generated nightly release on $(date -u +"%Y-%m-%d %T %Z")" \
            false \
            true
        }
        make_version_release()
        {
          github_create_release \
            "${1}" \
            "${GITHUB_SHA}" \
            "ares ${1}" \
            "This is ares ${1}, released on $(date +"%Y-%m-%d")." \
            false \
            false
        }
        case ${GITHUB_REF} in
          refs/tags/*)
            # Create a new version release using the current revision.
            echo "UPLOAD_URL=$(make_version_release ${GITHUB_REF#refs/tags/} | jq -r .upload_url)" >> $GITHUB_ENV
            ;;
          refs/heads/master)
            # Check for an existing nightly release.
            { release_id=$(github_get_release_id_for_tag nightly); status=$?; } || true
            # Delete existing nightly release if it exists.
            case ${status} in
              0) github_delete_release_by_id "${release_id}" ;;
              22) >&2 echo "No current nightly release; skipping tag deletion." ;;
              *) >&2 echo "API call failed unexpectedly." && exit 1 ;;
            esac
            # Create a new nightly release using the current revision.
            echo "UPLOAD_URL=$(make_nightly_release | jq -r .upload_url)" >> $GITHUB_ENV
            ;;
        esac
    - name: Upload ares-windows
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-windows.zip', asset_name: 'ares-windows.zip', asset_content_type: 'application/zip' }
    - name: Upload ares-windows-msvc-arm64
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-windows-msvc-arm64.zip', asset_name: 'ares-windows-msvc-arm64.zip', asset_content_type: 'application/zip' }
    - name: Upload ares-macos-latest
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-macos-latest.zip', asset_name: 'ares-macos-latest.zip', asset_content_type: 'application/zip' }
    - name: Upload ares-macos-compat
      uses: actions/upload-release-asset@v1
      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-macos-compat.zip', asset_name: 'ares-macos-compat.zip', asset_content_type: 'application/zip' }
#  - name: Upload ares-ubuntu
#      uses: actions/upload-release-asset@v1
#      env: { GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' }
#      with: { upload_url: '${{ env.UPLOAD_URL }}', asset_path: 'ares-ubuntu.zip', asset_name: 'ares-ubuntu.zip', asset_content_type: 'application/zip' }
