name: PR Run
on:
  pull_request:
    branches: [ '*' ]
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build-project:
    name: Build
    uses: ./.github/workflows/build-new.yml
    secrets: inherit
    permissions:
      contents: read
