name: Push
run-name: ${{ github.ref_name }} push run
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  build:
    name: Build ares
    uses: ./.github/workflows/build_new.yml
    secrets: inherit
    with:
      codesign: true
  release_job:
    runs-on: macos-latest
    name: Release Action
    needs: build
    secrets: inherit
    steps:
      - id: release_action
        uses: ./.github/actions/release
        with:
          notarize: true
